openapi: 3.0.3
info:
  title: Zouti API
  description: ...
  version: 1.0.0
servers:
  - url: http://localhost:3000/v1
    description: dev
  - url: https://api.zouti-stage.com.br/v1
    description: stage
  - url: https://apiv1.zouti.com.br/v1
    description: prod
tags:
  - name: _public
  - name: _public_global
  - name: _public_worker
  - name: _admin
  - name: domain
  - name: event
  - name: report
  - name: social
  - name: pixel
  - name: freight
  - name: promocode
  - name: checkout
  - name: checkout_customization
  - name: product
  - name: order
  - name: payment
  - name: auth
  - name: user
  - name: account
  - name: orderbump
  - name: upsell
  - name: shopify
  - name: demo
  - name: gateway
  - name: integration
paths:
  /auth/login:
    post:
      operationId: auth_login
      summary: Login
      tags:
        - auth
      security:
        - noAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: The email address of the user.
                password:
                  type: string
                  description: The password of the user in plain-text.
              required:
                - email
                - password
      responses:
        "200":
          description: ...
          headers:
            Set-Cookie:
              description: ...
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref:
                      "#/paths.users.post.responses.200.content.application_json.schema.prop\
                      erties.user"
                  token:
                    type: string
  /auth/forgot-password:
    post:
      operationId: auth_forgot_password
      summary: Forgot password
      tags:
        - auth
      security:
        - noAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: The email address of the user.
              required:
                - email
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /auth/reset-password:
    post:
      operationId: auth_reset_password
      summary: Reset password
      tags:
        - auth
      security:
        - noAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: The token for reset password.
                password:
                  type: string
                  description: The password for reset.
                password_confirmation:
                  type: string
                  description: The password_confirmation for reset.
              required:
                - token
                - password
                - password_confirmation
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /sessions/me:
    delete:
      operationId: session_me_delete
      summary: Delete Current Session
      tags:
        - auth
      security:
        - userAuth: []
      responses:
        "204":
          description: The session was deleted successfully.
  /users:
    post:
      operationId: user_create
      summary: Create User
      tags:
        - user
      security:
        - noAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the user.
                email:
                  type: string
                  format: email
                  description: The email address of the user.
                password:
                  type: string
                  description: The password of the user in plain-text.
                phone:
                  type: string
                  description: The phone number of the user.
              required:
                - name
                - email
                - password
                - phone
      responses:
        "200":
          description: ...
          headers:
            Set-Cookie:
              description: ...
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        description: The unique identifier for the user.
                      name:
                        type: string
                        description: The name of the user.
                      email:
                        type: string
                        format: email
                        description: The email address of the user.
                      phone:
                        type: string
                        description: The phone of the user.
                      created_at:
                        type: string
                        format: date-time
                        description: The date and time when the user was created.
                      updated_at:
                        type: string
                        format: date-time
                        description: The date and time when the user was last updated.
                    required:
                      - id
                      - name
                      - email
                      - created_at
                      - updated_at
                    x-zouti-object:
                      scopes:
                        - read
                      events: []
                  token:
                    type: string